version: '3.4'

services:
  badges:
    image: badges
    container_name: badges-prod
    build:
      context: .
      dockerfile: ./functions/Dockerfile
    environment:
      NODE_ENV: production
      API_SECRET_KEY: HSIv0qtRxUTCLizJdm2WD
    ports:
      - 8400:3000
    expose:
      - "8400"
    restart: always
